name: Smoke
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          # Optional sentence splitter
          python -m pip install blingfire

      - name: Login to Docker (not required for public images)
        run: docker --version

      - name: Run smoke (fresh by default; skip LLM)
        env:
          OPENAI_API_KEY: ""                  # ensure LLM step is skipped
          CHUNK_MODE: sentence                # exercise sentence mode in CI
          SENT_SPLITTER: blingfire
          PDF_BACKEND: pdfminer               # or pymupdf if you installed it
        run: |
          chmod +x ./smoke_e2e.sh
          ./smoke_e2e.sh

